url: ""
baseurl: ""

markdown: kramdown
timezone: Asia/Tokyo

plugins:
  - jekyll-seo-tag

collections:
  - publications
  - news

exclude:
  - vendor
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
